### ISSUE TITLE
Doubled Hyperlines on macOS

### ISSUE THREAD

**Issue by aewing** [NickTikhonov/hyperterm-hyperline#16]
Occasionally hyperline will be duplicated in my HyperTerm sessions after resizing the window or unplugging a monitor. I'm having trouble reproducing the issue consistently, but it can be quite bothersome when it does occur.

I am on the beta build of macOS, but a friend who is on the latest supported build has confirmed that they are seeing the issue as well.

I am using Node v6.3.1

**Comment by timneutkens** [comment]
I've experienced this myself, as you said, inconsistently. Will have a look at fixing it 👍

**Comment by timneutkens** [comment]
Seems fixed when we moved to the higher order component way. Closing.
