### ISSUE TITLE
HyperLine Plugin Error

### ISSUE THREAD

**Issue by Craytor** [NickTikhonov/hyperterm-hyperline#17]
I am getting the following error when I try to install the plugin:
```
[Notification] Plugin load error: "hyperline" failed to load in the renderer process. Check Developer Tools for details.
```

Here is the full error in the Developer Tools console:
<img width="1299" alt="screen shot 2016-08-21 at 4 29 27 pm" src="https://cloud.githubusercontent.com/assets/3680866/17839657/85ce06da-67bc-11e6-9689-82fe8057f65a.png">

**Comment by MadlySeason** [comment]
I have the same issue and if my memory is any good, this was not happening before I started using [https://github.com/matheuss/hpm](hpm-cli).
Please let me know how I can help.

**Comment by Craytor** [comment]
@MadlySeason Hmm, I don't have that installed.

**Comment by NickTikhonov** [comment]
Hey @Craytor @MadlySeason - apologies for the problem. It was caused by an incorrect configuration of our package which prevented the transpiled JavaScript from being published to NPM. This was fixed, and the updated version should work just fine :) Let me know if you have any more issues

**Comment by Craytor** [comment]
This has fixed the errors! Also, are the hours listed at the bottom of the console how long the computer has been on?

**Comment by MadlySeason** [comment]
@Craytor 
If you check [index.js](https://github.com/NickTikhonov/hyperterm-hyperline/blob/master/src/index.js) you can see what each item is.
First is hostname, then memory status, then **uptime** and last cpu status.
