### ISSUE TITLE
Cloned hyperline repo fails to load

### ISSUE THREAD

**Issue by Or3stis** [NickTikhonov/hyperterm-hyperline#19]
While installing the plugin using `hpm-cli` I have no issues and works perfectly. It fails to load when I clone the repo for development. Here is a screenshot of the issue.

<img width="548" alt="screen shot 2016-08-26 at 11 14 01" src="https://cloud.githubusercontent.com/assets/11923550/18002188/43db4876-6b7e-11e6-9610-ad8d872dfa0c.png">

The cloned repo is at 

<img width="381" alt="screen shot 2016-08-26 at 11 17 48" src="https://cloud.githubusercontent.com/assets/11923550/18002293/c39acae6-6b7e-11e6-8c30-2927623f791e.png">

My .hyperterm.js
<img width="408" alt="screen shot 2016-08-26 at 11 19 13" src="https://cloud.githubusercontent.com/assets/11923550/18002316/f2558f74-6b7e-11e6-97b8-498c6f9b5626.png">

Is there something else I must do in order to make it work, besides cloning the repo at the `hyperterm_plugins/local` folder?

**Comment by JerryLopez** [comment]
@Or3stis try the following steps and let me know if they work out for you. I'm submitting a PR for this.

To set up the project for development:

1. Clone this repository into `~/.hyperterm_plugins/local/`
2. Run `npm install` within the project directory
3. Run `npm run build` to build the plugin **OR** `npm run dev` to build the plugin and watch for file changes.
4. Add the name of the directory to `localPlugins` in `~/.hyperterm.js`.
5. Reload terminal window

**Comment by Or3stis** [comment]
It works great 👍 !!

Thank you @JerryLopez
