### ISSUE TITLE
Blurry text on high dpi monitor

### ISSUE THREAD

**Issue by jimthedev** [NickTikhonov/hyperterm-hyperline#2]
Hi there. Great plugin. One thing I've noticed is that on my 13in retina mbp, the text is super blurry. I'm guessing this is due to using canvas w/o adjusting for dpi. http://www.html5rocks.com/en/tutorials/canvas/hidpi/

**Comment by NickTikhonov** [comment]
Hi @jimthedev - thanks for pointing this out 👍 . This is definitely a result of using canvas instead of rendering the line as a DOM element. I'm planning to reimplement the line to render in the DOM, but I will fix this issue ASAP :)

**Comment by NickTikhonov** [comment]
@jimthedev - this problem has been fixed with #5, let me know if you have any issues :)
