### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by NickTikhonov** [NickTikhonov/hyperterm-hyperline#30]
This issue's purpose is to discuss how Hyperline will be configured by it's users. A means of customising and configuring Hyperline would be really useful, especially as we have more and more plugins available. Users should be able to:

* Select which plugins they want to see
* Change the color associated with each plugin
* Change the font size of all plugins (or perhaps size relative to the terminal font size)
* Change the order of plugins
* Have the configuration available in a file, for easy backup 

This is easily achievable through an object in `.hyperterm.js` that the user can edit. While this is a great first step, I think we could have a more intuitive interface as well. The two ideas I've got are a plugin configuration tab in the terminal, or alternatively, drag and drop functionality coupled with right-click menus for each plugin. Either option would make changes to `.hyperterm.js` to reflect the changes made using the UI. 

Whatever we choose, this will be an awesome feature to ship with the next release 😄 Would love to hear your thoughts!

**Comment by davegomez** [comment]
I like all the ideas and I think they are necessary.

I specially like the drag and drop option, very fancy xD

**Comment by NickTikhonov** [comment]
There are libraries available that make drag and drop possible, the best i found so far is [React DnD](https://github.com/gaearon/react-dnd). The only problem is that it needs React as a peer dependency, so we might have to that into our module after all 😂

**Comment by Or3stis** [comment]
The configuration option is becoming essential (we are running out of room 😃)

I was planning on making some plugins for security testing such as:
* external IP
* local IP
* what interfaces are up
* interface mode
* whether the mac address is changed

Since those plugins are pretty specific, it makes little sense to ship in the default version.

What are the general plans for hyperterm's configuration. Are they going to make a GUI or stick with the `hyperterm.js`?

**Comment by NickTikhonov** [comment]
@Or3stis - wow awesome :D I think we should start with a config object in `.hyperterm.js` and eventually add something that's easier to use

**Comment by davegomez** [comment]
We should create a route map with the selected plans not the ideas, the ideas could be somewhere else.

We need a way to order the future features so we can pick them one by one.
