### ISSUE TITLE
NaNKb/s in traffic display

### ISSUE THREAD

**Issue by ryedin** [NickTikhonov/hyperterm-hyperline#43]
The attached screenshot says it all. NOTE: this is intermittent (it flickers between this and 0KB/s at times)

<img width="279" alt="screen shot 2016-10-05 at 11 55 15 am" src="https://cloud.githubusercontent.com/assets/151376/19123061/d634f3c8-8af2-11e6-86e7-ee0947a487ad.png">

**Comment by timneutkens** [comment]
Fixed in the next release. There was a PR to fix it already :) Thanks for pointing it out Anyways!
