### ISSUE TITLE
getting NaNkb/s during npm installs

### ISSUE THREAD

**Issue by jkup** [NickTikhonov/hyperterm-hyperline#45]
Seeing this a lot when I npm install on a  project. The traffic reader gets in a weird state where it alternates between 0 and NaNkb/s.

<img width="228" alt="screen shot 2016-10-06 at 4 06 21 pm" src="https://cloud.githubusercontent.com/assets/490294/19173828/1c3820b0-8bdf-11e6-971f-2f8594444e09.png">

**Comment by timneutkens** [comment]
Fixed in next release soon.
