### ISSUE TITLE
long time launching 

### ISSUE THREAD

**Issue by tkisme** [NickTikhonov/hyperterm-hyperline#46]
need 5 more seconds to launch a new windows

**Comment by davegomez** [comment]
Can you provide more context on this issue @tkisme?

**Comment by tkisme** [comment]
Darwin Kernel Version 16.0.0
hyper:0.8.2

**Comment by timneutkens** [comment]
@tkisme can you provide some actual example? Kinda hard to debug without it. For me personally it's just as fast. We don't do anything render blocking in Hyperline (all async). So this shouldn't be an issue 🤔

**Comment by tkisme** [comment]
TypeError: this.setBatteryStatus is not a functio

**Comment by timneutkens** [comment]
> TypeError: this.setBatteryStatus is not a function
is fixed now.

the render time is in `ms` so render time increased with around `100ms`, not sure why that is. But it's still kinda fast 😏 at least it's not 5 seconds more, that would be terrible 😉

**Comment by tkisme** [comment]
total init time 359.82
