### ISSUE TITLE
Conflicts with Hyperborder

### ISSUE THREAD

**Issue by jkup** [NickTikhonov/hyperterm-hyperline#6]
Hey!

Not sure what repo to report this in but this plugin seems to conflict with [Hyperborder](https://github.com/webmatze/hyperborder)

Screenshot attached:
![screen shot 2016-07-20 at 3 26 51 pm](https://cloud.githubusercontent.com/assets/490294/17005335/7dcaede6-4e8e-11e6-9023-a3696c364fa3.png)

**Comment by NickTikhonov** [comment]
Hey @jkup - thanks for pointing this out! It would make sense to resolve this on our end - hyperborder applies CSS styling to the window, while hyperline draws a canvas overlay. I'll take a look at fixing this :)

**Comment by ruiposse** [comment]
It doesn't conflict only with Hyperborder. If you open vim, hyperline goes a bit on top of the vim "prompt" (that is obviously in the bottom).
