### ISSUE TITLE
Local development issues

### ISSUE THREAD

**Issue by timneutkens** [NickTikhonov/hyperterm-hyperline#8]
Following the instructions in README.md I installed hyperline locally. Whenever I start hyperterm or refresh the window I see the following error: `Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'` on line 134 of index.js. This is triggered because this._canvas is null. Doing some debugging I found out _onTerminal is not triggered. Did you see this before?
<img width="1552" alt="screen shot 2016-07-23 at 21 24 00" src="https://cloud.githubusercontent.com/assets/6324199/17079825/d18cc118-511b-11e6-8ff1-66b7e88cb7ae.png">

**Comment by NickTikhonov** [comment]
Hey @timneutkens  - that is definitely strange. I'll take a look and see if I can replicate this.

**Comment by NickTikhonov** [comment]
I just removed my local development version and reinstalled it again - I didn't get any errors.

First, I ran:

```
cd ~/.hyperterm_plugins/local/
git clone https://github.com/NickTikhonov/hyperterm-hyperline.git
vim ~/.hyperterm.js
```

Then I added "hyperterm-hyperline" to localPlugins:

```
 localPlugins: [                                                                
    "hyperterm-hyperline"                                                        
 ]
```

I'm on the latest version of HyperTerm, and have no other plugins installed. It might be useful if you could list all other plugins you have installed :)

**Comment by timneutkens** [comment]
should note that when I add it to plugins everything is fine, just removed all plugins. Now it seems to function properly 👍 just have to figure out which plugin is killing it. I have these `'hypercwd', 'hyperterm-atom-dark', 'hyperterm-1password', 'hyperterm-blink'`

**Comment by timneutkens** [comment]
hmmm that's just plain weird. Removed all plugins, restarted, added them back one by one. Everything was fine. Updated all plugins. Now it's all functioning properly. Thanks Nick!

**Comment by NickTikhonov** [comment]
No problem, glad it worked in the end  👍
